openapi: 3.0.0
info:
  title: DjjsEventReporting
  version: 1.0.0
  description: API documentation for the DjjsEventReporting application

servers:
  - url: https://eventsreportingapidev.djjs.org/admin 
    description: Development server
  - url: http://localhost:8080/admin
    description: Local development server

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /eventHistory/post:
    $ref: "./paths/eventHistory.yaml"
  /users:
    $ref: "./paths/user.yaml"
  /users/login:
    $ref: "./paths/login.yaml"
  /branches/search:
    $ref: "./paths/branch.yaml"


