openapi: 3.0.0
info:
  title: DjjsEventReporting
  version: 1.0.0
  description: API documentation for the DjjsEventReporting application

servers:
  - url: https://gateway-dev-api.djjs.com/chat
    description: Development server
  - url: http://localhost:8050/admin
    description: Local development server

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /eventHistory/post:
    $ref: "./paths/eventHistory.yaml#/post"
  /users/create:
    $ref: ./paths/user.yaml
  /users/login:
    $ref: ./paths/login.yaml



