openapi: 3.0.0
info:
  title: DjjsEventReporting
  version: 1.0.0
  description: API documentation for the DjjsEventReporting application
servers:
  - url: 'https://gateway-dev-api.djjs.com/chat'
    description: Development server
  - url: 'http://localhost:8050/admin'
    description: Local development server
components: {}
paths:
  /eventHistory/post:
    post:
      summary: Create a new Event History record
      description: Add a new Event History to the database.
      tags:
        - EventHistory
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - event_history
                - guest_masters
                - media_and_docs
                - program_donations
                - program_volunteers
              properties:
                event_history:
                  type: object
                  required:
                    - fk_program_master_id
                    - fk_branch_id
                    - start_date
                    - end_date
                  properties:
                    fk_program_master_id:
                      type: string
                      description: ID of the program master.
                    fk_branch_id:
                      type: string
                      description: ID of the branch.
                    start_date:
                      type: string
                      format: date
                      description: Start date of the event.
                    end_date:
                      type: string
                      format: date
                      description: End date of the event.
                guest_masters:
                  type: object
                  properties:
                    guest_id:
                      type: string
                      description: ID of the guest.
                    name:
                      type: string
                      description: Name of the guest.
                    contact_number:
                      type: string
                      description: Contact number of the guest.
                media_and_docs:
                  type: object
                  required:
                    - file_type
                    - file_url
                  properties:
                    file_type:
                      type: string
                      description: 'Type of the media or document (e.g., image, video, document).'
                    file_url:
                      type: string
                      description: URL of the media or document.
                program_donations:
                  type: object
                  required:
                    - donation_id
                    - amount
                    - donor_name
                  properties:
                    donation_id:
                      type: integer
                      description: ID of the donation.
                    amount:
                      type: number
                      format: float
                      description: Amount donated.
                    donor_name:
                      type: string
                      description: Name of the donor.
                program_volunteers:
                  type: object
                  required:
                    - volunteer_id
                    - volunteer_name
                    - hours_volunteered
                  properties:
                    volunteer_id:
                      type: integer
                      description: ID of the volunteer.
                    volunteer_name:
                      type: string
                      description: Name of the volunteer.
                    hours_volunteered:
                      type: number
                      format: float
                      description: Total hours volunteered.
      responses:
        '201':
          description: Event history created successfully
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/paths/~1eventHistory~1post/post/requestBody/content/application~1json/schema'
                  - type: object
                    properties:
                      id:
                        type: integer
                      created_on:
                        type: string
                        format: date-time
                      updated_on:
                        type: string
                        format: date-time
        '400':
          description: Invalid input
