name: Go

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Build Go app
      run: go build -o main ./cmd/main/main.go

    - name: Test
      run: go test -v ./...

    # Optional: If you have frontend or npm part
    # - name: Build frontend
    #   run: npm run build --if-present

    - name: Restart PM2 process
      run: pm2 restart djjs-go-server || pm2 start "go run ." --name djjs-go-server
